### ISSUE TITLE
Generate the package list file after installing a module

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/nuclear#4]

**Comment by MrNaif2018** [comment]
Hi! I would like to help with this!
What format should package list file format?
Is it some kind of a lock file (like `yarn.lock`, `Poetry.lock`, etc.), or just a simple text file listing installed packages?

**Comment by SuperFola** [comment]
Hi!

It's like a yarn.lock file, it should have those kind of fields:
* package name
* version
* deps (with version)

The rest is mostly optional for now I think (description, author), we can always add that later in the future!

**Comment by MrNaif2018** [comment]
And a sha256 hash and url possibly too.
Thanks, will work on it soon
